"""DocGen — Documentation Generator powered by Gemma."""

import streamlit as st

from core import gemma_engine
from core.obsidian_export import export_study_guide
from core.page_state import ensure_state, set_result
from core.sidebar import render_sidebar
from core.ui_components import inject_global_css, page_header

st.set_page_config(page_title="DocGen", page_icon="📝", layout="wide")
inject_global_css()
model_config = render_sidebar("docgen")

page_header("📝", "DocGen — AI Documentation Generator", "Paste code or describe a project — get professional documentation generated by Gemma 4.", badge="Docs")

ensure_state(
    docgen_code_result="",
    docgen_project_result="",
    docgen_project_type="",
    docgen_project_name="",
    docgen_readme_result="",
    docgen_readme_name="",
)

tab_code, tab_project, tab_readme = st.tabs(["Code Documentation", "Project Docs", "README Generator"])


with tab_code:
    code = st.text_area("Paste code to document", height=250, key="doc_code")
    col1, col2 = st.columns(2)
    with col1:
        language = st.text_input("Language", "Python", key="doc_lang")
    with col2:
        doc_style = st.selectbox("Documentation style", [
            "Google style", "NumPy style", "Sphinx/RST", "JSDoc", "Javadoc",
        ])

    if st.button("Generate Documentation", type="primary", key="btn_code_doc") and code.strip():
        prompt = f"""Add comprehensive documentation to the following {language} code using {doc_style} conventions.

```{language.lower()}
{code}
```

Requirements:
- Add docstrings/comments to all functions, classes, and modules
- Include parameter types and descriptions
- Document return values and exceptions
- Add inline comments for complex logic only
- Include usage examples in docstrings
- Preserve all original code — only ADD documentation

Output the fully documented code."""

        config = gemma_engine.GemmaConfig(model=model_config.model, temperature=0.2, max_tokens=6000)
        config.system_prompt = f"You are an expert technical writer specializing in {language} documentation."

        placeholder = st.empty()
        with st.spinner("Documenting code..."):
            result = gemma_engine.generate(prompt, config, stream_callback=lambda t: placeholder.markdown(t))
        placeholder.markdown(result)
        set_result("docgen_code_result", result)

    if st.session_state.docgen_code_result:
        st.markdown(st.session_state.docgen_code_result)
        code_export, code_download = st.columns(2)
        if code_export.button("Export Documented Code", key="doc_code_export"):
            path = export_study_guide("DocGen Code Documentation", st.session_state.docgen_code_result, tags=["docgen", "code-docs"])
            st.success(f"Exported to: {path}")
        code_download.download_button(
            "Download Markdown",
            data=st.session_state.docgen_code_result,
            file_name="documented_code.md",
            mime="text/markdown",
            key="doc_code_download",
        )

with tab_project:
    project_name = st.text_input("Project name", key="proj_name")
    project_desc = st.text_area("Describe the project", height=150, key="proj_desc",
                                 placeholder="e.g. A REST API for managing a library — book CRUD, user auth, borrowing system, with PostgreSQL and FastAPI")
    doc_type = st.selectbox("Documentation type", [
        "Technical Design Document", "API Documentation",
        "User Guide", "Contributing Guide", "Architecture Decision Record",
        "Deployment Guide", "Testing Strategy",
    ])

    if st.button("Generate", type="primary", key="btn_proj") and project_desc.strip():
        prompts = {
            "Technical Design Document": f"""Write a Technical Design Document for:

**Project:** {project_name or 'See description'}
**Description:** {project_desc}

Include: Overview, Goals & Non-Goals, Architecture, Data Models, API Design, Security Considerations, Testing Strategy, Deployment Plan, Open Questions.""",

            "API Documentation": f"""Write API documentation for:

**Project:** {project_name}
**Description:** {project_desc}

Include: Overview, Authentication, Base URL, Endpoints (grouped by resource), Request/Response examples, Error codes, Rate limits, Pagination.""",

            "User Guide": f"""Write a User Guide for:

**Project:** {project_name}
**Description:** {project_desc}

Include: Getting Started, Installation, Configuration, Core Features (with examples), FAQ, Troubleshooting, Glossary.""",

            "Contributing Guide": f"""Write a Contributing Guide for:

**Project:** {project_name}
**Description:** {project_desc}

Include: How to Contribute, Development Setup, Code Style, Branch Strategy, PR Process, Testing Requirements, Code Review Checklist.""",

            "Architecture Decision Record": f"""Write Architecture Decision Records for:

**Project:** {project_name}
**Description:** {project_desc}

For each key architectural decision, use the ADR format:
- Title, Status, Context, Decision, Consequences.
Identify 3-5 key architectural decisions.""",

            "Deployment Guide": f"""Write a Deployment Guide for:

**Project:** {project_name}
**Description:** {project_desc}

Include: Prerequisites, Environment Setup, Configuration, Build Steps, Deployment Steps (dev/staging/prod), Monitoring, Rollback Procedures, Health Checks.""",

            "Testing Strategy": f"""Write a Testing Strategy document for:

**Project:** {project_name}
**Description:** {project_desc}

Include: Test Pyramid (unit/integration/e2e), Test Categories, Coverage Goals, Test Data Management, CI/CD Integration, Performance Testing, Security Testing.""",
        }

        prompt = prompts.get(doc_type, prompts["Technical Design Document"])

        config = gemma_engine.GemmaConfig(model=model_config.model, temperature=0.4, max_tokens=6000)
        config.system_prompt = "You are a senior technical writer. Write clear, comprehensive, well-structured documentation."

        placeholder = st.empty()
        with st.spinner(f"Generating {doc_type}..."):
            result = gemma_engine.generate(prompt, config, stream_callback=lambda t: placeholder.markdown(t))
        placeholder.markdown(result)
        set_result("docgen_project_result", result)
        set_result("docgen_project_type", doc_type)
        set_result("docgen_project_name", project_name or "Project")

    if st.session_state.docgen_project_result:
        st.markdown(st.session_state.docgen_project_result)
        if st.button("Export to Obsidian", key="export_proj"):
            path = export_study_guide(
                f"{st.session_state.docgen_project_type or doc_type} - {st.session_state.docgen_project_name or project_name or 'Project'}",
                st.session_state.docgen_project_result,
                tags=["docgen", (st.session_state.docgen_project_type or doc_type).lower().replace(" ", "-")],
            )
            st.success(f"Exported to: {path}")
        st.download_button(
            "Download Markdown",
            data=st.session_state.docgen_project_result,
            file_name="project_documentation.md",
            mime="text/markdown",
            key="doc_project_download",
        )

with tab_readme:
    readme_name = st.text_input("Project name", key="readme_name")
    readme_desc = st.text_area("Brief project description", height=100, key="readme_desc")
    col1, col2 = st.columns(2)
    with col1:
        readme_lang = st.text_input("Primary language/framework", key="readme_lang", placeholder="e.g. Python / FastAPI")
    with col2:
        readme_license = st.selectbox("License", ["MIT", "Apache 2.0", "GPL 3.0", "BSD 3-Clause", "Unlicensed"])

    features = st.text_area("Key features (one per line)", height=80, key="readme_features",
                              placeholder="Real-time notifications\nUser authentication\nRESTful API")

    if st.button("Generate README", type="primary", key="btn_readme") and readme_desc.strip():
        prompt = f"""Generate a professional README.md for:

**Project:** {readme_name}
**Description:** {readme_desc}
**Tech:** {readme_lang}
**License:** {readme_license}
**Features:**
{features}

Include sections: Project Title + badges, Description, Features, Installation, Quick Start, Usage Examples, Configuration, API Reference (brief), Contributing, License.
Use proper Markdown with shields.io badge placeholders."""

        config = gemma_engine.GemmaConfig(model=model_config.model, temperature=0.4, max_tokens=4000)
        placeholder = st.empty()
        with st.spinner("Generating README..."):
            result = gemma_engine.generate(prompt, config, stream_callback=lambda t: placeholder.markdown(t))
        placeholder.markdown(result)
        set_result("docgen_readme_result", result)
        set_result("docgen_readme_name", readme_name or "Project")

    if st.session_state.docgen_readme_result:
        st.markdown(st.session_state.docgen_readme_result)
        readme_export, readme_download = st.columns(2)
        if readme_export.button("Export README to Obsidian", key="doc_readme_export"):
            path = export_study_guide(
                f"README - {st.session_state.docgen_readme_name or readme_name or 'Project'}",
                st.session_state.docgen_readme_result,
                tags=["docgen", "readme"],
            )
            st.success(f"Exported to: {path}")
        readme_download.download_button(
            "Download README.md",
            data=st.session_state.docgen_readme_result,
            file_name="README.md",
            mime="text/markdown",
            key="doc_readme_download",
        )
